// <auto-generated/> — produced by the settings-slice generator from the
// pre-refactor AppSettings.cs. Do not hand-edit; the numbers are the
// frozen pre-slice contract. Update only by re-running the generator.
using DeskBox.Models;
using Xunit;

namespace DeskBox.Tests;

public sealed class SettingsSliceContractBaselineTests
{
    [Fact]
    public void FacadeDefaults_MatchPreSliceValues()
    {
        var s = new AppSettings();
        Assert.Equal("System", s.Theme);
        Assert.Equal("Colorful", s.TrayIconStyle);
        Assert.Equal("System", s.Language);
        Assert.Equal("System", s.AccentColorMode);
        Assert.Equal("#0078D4", s.CustomAccentColor);
        Assert.True(s.AutoStart);
        Assert.False(s.AutoStartDefaultApplied);
        Assert.Null(s.AutoStartMode);
        Assert.Equal("ResourceSaver", s.PerformanceMode);
        Assert.Equal(30, s.HiddenCacheCleanupDelaySeconds);
        Assert.Equal("AllRecreatable", s.HiddenCacheCleanupScope);
        Assert.Equal(5 * 60, s.VisibleIdleCacheCleanupDelaySeconds);
        Assert.True(s.IdleWorkingSetTrimEnabled);
        Assert.True(s.ImmediateHiddenWorkingSetTrimEnabled);
        Assert.True(s.QuiescenceWorkingSetTrimEnabled);
        Assert.Equal(2 * 60, s.TransientWindowReleaseDelaySeconds);
        Assert.Equal("Small", s.PerformanceCacheBudget);
        Assert.True(s.EnableContinuousDecorativeAnimations);
        Assert.True(s.EnableTextMarqueeAnimations);
        Assert.True(s.EnableVinylRotationAnimations);
        Assert.True(s.EnableGlanceImageAutoRotation);
        Assert.True(s.EnableCompactAmbientAnimations);
        Assert.True(s.AutoCheckForUpdates);
        Assert.Null(s.LastUpdateCheckAt);
        Assert.False(s.QuickCaptureEnabled);
        Assert.False(s.TodoEnabled);
        Assert.Empty(s.FeatureWidgetEnabledStates);
        Assert.False(s.QuickCaptureClipboardEnabled);
        Assert.False(s.QuickCaptureImageClipboardEnabled);
        Assert.Equal(30, s.QuickCaptureRecentLimit);
        Assert.True(s.QuickCaptureShowCreatedTime);
        Assert.Equal(3, s.QuickCaptureItemPreviewLineCount);
        Assert.Equal(0d, s.QuickCaptureListTextSize);
        Assert.Equal(0d, s.QuickCaptureContentTextSize);
        Assert.Equal("CtrlEnterSaves", s.QuickCaptureEditorEnterBehavior);
        Assert.Equal("Markdown", s.QuickCaptureDefaultFormat);
        Assert.Equal("Auto", s.QuickCaptureWideLayout);
        Assert.Equal("Reading", s.QuickCaptureWideOpenMode);
        Assert.False(s.QuickCaptureAllowRemoteImages);
        Assert.Equal("Link", s.AttachmentStorageMode);
        Assert.Equal("Records", s.QuickCaptureDefaultView);
        Assert.Equal("Button", s.QuickCaptureTabStyle);
        Assert.True(s.QuickCaptureShowTabBar);
        Assert.True(s.QuickCaptureShowRecordsTab);
        Assert.True(s.QuickCaptureShowPinnedTab);
        Assert.True(s.QuickCaptureShowRecentTab);
        Assert.Equal("Top", s.TodoNewTaskPosition);
        Assert.Equal("Button", s.TodoTabStyle);
        Assert.True(s.TodoShowTabBar);
        Assert.True(s.TodoShowAllTab);
        Assert.False(s.TodoShowActiveTab);
        Assert.True(s.TodoShowTodayTab);
        Assert.False(s.TodoShowThisWeekTab);
        Assert.False(s.TodoShowThisMonthTab);
        Assert.True(s.TodoShowImportantTab);
        Assert.True(s.TodoShowCompletedTab);
        Assert.Equal("All", s.TodoDefaultFilter);
        Assert.False(s.TodoShowCompletedTasks);
        Assert.Equal(2, s.TodoItemPreviewLineCount);
        Assert.Equal(0d, s.TodoListTextSize);
        Assert.Equal(0d, s.TodoContentTextSize);
        Assert.Equal("CtrlEnterSaves", s.TodoEditorEnterBehavior);
        Assert.False(s.TodoShowFooterStats);
        Assert.True(s.TodoShowClearCompletedButton);
        Assert.True(s.TodoReminderEnabled);
        Assert.Equal(5, s.TodoDefaultReminderOffsetMinutes);
        Assert.True(s.TodoUseWideDetailPane);
        Assert.Equal(string.Empty, s.TodoLayoutMode);
        Assert.True(s.TodoAutoSelectFirstInWideLayout);
        Assert.True(s.MusicUseArtworkBackdrop);
        Assert.True(s.MusicEnableCoverHoverMotion);
        Assert.Equal("Auto", s.MusicDisplayMode);
        Assert.Equal(string.Empty, s.LastQuickCaptureFileWidgetId);
        Assert.True(s.GlobalHotkeyEnabled);
        Assert.Equal(HotkeyActivationKind.Chord, s.GlobalHotkeyActivationKind);
        Assert.Equal((int)HotkeyModifierKeys.None, s.GlobalHotkeyModifiers);
        Assert.Equal((int)Windows.System.VirtualKey.F7, s.GlobalHotkeyKey);
        Assert.False(s.DesktopDoubleClickEnabled);
        Assert.False(s.HasCompletedOnboarding);
        Assert.Equal(0, s.OnboardingStepIndex);
        Assert.Equal(0, s.CompletedOnboardingVersion);
        Assert.False(s.HasResolvedInitialFileWidgetSetup);
        Assert.Equal(280, s.DefaultWidgetWidth);
        Assert.Equal(400, s.DefaultWidgetHeight);
        Assert.Equal(0.80, s.WidgetOpacity);
        Assert.Equal("Mica", s.WidgetMaterialType);
        Assert.Equal(0.65, s.WidgetMaterialIntensity);
        Assert.Equal("FollowTheme", s.WidgetForegroundMode);
        Assert.Equal("#F5F5F5", s.WidgetForegroundColor);
        Assert.Equal("Neutral", s.WidgetBorderColorMode);
        Assert.Equal("Thin", s.WidgetBorderStyle);
        Assert.Equal("Round", s.WidgetCornerPreference);
        Assert.Equal("SlideFade", s.WidgetAnimationEffect);
        Assert.Equal("Standard", s.WidgetAnimationSpeed);
        Assert.Equal("Right", s.WidgetAnimationSlideDirection);
        Assert.Equal("Standard", s.WidgetAnimationEasingIntensity);
        Assert.Equal("Dynamic", s.WidgetLayerMode);
        Assert.True(s.KeepWidgetsVisibleOnShowDesktop);
        Assert.Equal("Overlay", s.DisplayWidgetChromeMode);
        Assert.Equal("Standard", s.InteractiveWidgetChromeMode);
        Assert.Equal("Expanded", s.WidgetCollapseBehavior);
        Assert.Null(s.LegacyWidgetCapsuleModeEnabled);
        Assert.Equal("Aligned", s.WidgetCompactWidthMode);
        Assert.Equal("Down", s.WidgetCompactExpansionDirection);
        Assert.Equal("Free", s.WidgetCapsuleArrangementMode);
        Assert.Equal(8, s.WidgetCapsuleBarSpacing);
        Assert.Equal("Floating", s.WidgetCapsuleBarPlacement);
        Assert.Equal("Auto", s.WidgetCapsuleBarDirection);
        Assert.Empty(s.WidgetCapsuleBarOrder);
        Assert.Empty(s.WidgetCapsuleFreePlacements);
        Assert.Equal("Smart", s.WidgetCollapsedStyle);
        Assert.Equal("Smart", s.WidgetCompactContentMode);
        Assert.False(s.WidgetCompactHideSensitiveContent);
        Assert.Equal(0, s.WidgetCompactSettingsVersion);
        Assert.Equal("Slow", s.WidgetCompactAnimationEffect);
        Assert.Equal(360, s.WidgetCompactAnimationDurationMs);
        Assert.Equal(100, s.WidgetCompactExpandDelayMs);
        Assert.Equal(200, s.WidgetCompactCollapseDelayMs);
        Assert.Equal("FollowWidget", s.WidgetCompactMediaCornerMode);
        Assert.Equal("Color", s.WidgetTitleIconMode);
        Assert.True(s.DoubleClickToOpen);
        Assert.Equal("Explorer", s.FileWidgetFolderOpenBehavior);
        Assert.False(s.FileItemSystemContextMenuEnabled);
        Assert.True(s.HideShortcutArrowOverlay);
        Assert.False(s.ShowImageFilesAsIcons);
        Assert.True(s.ShowHoverButtons);
        Assert.Equal("Add,More", s.WidgetHoverButtonActions);
        Assert.True(s.ResizeSnapEnabled);
        Assert.Equal(5, s.WidgetSnapSpacing);
        Assert.False(s.ShowListItemDetails);
        Assert.True(s.ShowFileItemPathTooltips);
        Assert.True(s.FileStacksEnabled);
        Assert.False(s.FileStackAutoStacking);
        Assert.Equal("Kind", s.FileStackGroupBy);
        Assert.Equal(3, s.FileStackThreshold);
        Assert.Equal("Widget", s.FileStackOrderBy);
        Assert.Equal("Inline", s.FileStackOpenMode);
        Assert.Equal("Grid3", s.FileStackPopoverLayout);
        Assert.Equal("Neutral", s.FileStackPopoverStyle);
        Assert.Empty(s.FileStackCustomRules);
        Assert.Equal("KeepLoose", s.FileStackUnmatchedBehavior);
        Assert.Equal("Move", s.ManagedDropAction);
        Assert.Equal(string.Empty, s.DefaultManagedStorageRootPath);
        Assert.False(s.ManagedStorageDesktopShortcutEnabled);
        Assert.Equal(string.Empty, s.ManagedStorageDesktopShortcutPath);
        Assert.True(s.AutomaticBackupEnabled);
        Assert.Equal(24 * 60, s.AutomaticBackupIntervalMinutes);
        Assert.Equal(7, s.AutomaticBackupRetentionCount);
        Assert.Equal(string.Empty, s.AutomaticBackupDirectory);
        Assert.Empty(s.RecentOrganizationHistory);
        Assert.Empty(s.DesktopOrganizationRules);
        Assert.False(s.DesktopAutoOrganizationEnabled);
        Assert.Null(s.DesktopAutoOrganizationBaselineUtc);
        Assert.Equal(30, s.IconSize);
        Assert.Equal(11.5, s.TextSize);
        Assert.Equal("Standard", s.LayoutDensity);
        Assert.Equal(0.56, s.LayoutDensityScale);
        Assert.Equal(0.40, s.HorizontalSpacingScale);
        Assert.Equal(0.60, s.VerticalSpacingScale);
        Assert.Equal(0.36, s.FileNameWidthScale);
        Assert.Equal(2, s.FileNameLineCount);
        Assert.False(s.ShowFileExtensions);
        Assert.True(s.HideShortcutExtensionWhenShowingFileExtensions);
        Assert.Empty(s.Widgets);
        Assert.Empty(s.WidgetGroups);
        Assert.Empty(s.WidgetTopologyLayouts);
        Assert.Null(s.ActiveWidgetTopologyKey);
        Assert.True(s.WidgetGroupsEnabled);
        Assert.Equal("Tabs", s.WidgetGroupDefaultNavigationStyle);
        Assert.Equal(WidgetGroupTitleDisplayModes.IconAndText, s.WidgetGroupDefaultTitleDisplayMode);
        Assert.True(s.WidgetGroupWheelSwitchEnabled);
        Assert.False(s.WidgetGroupHoverSwitchEnabled);
        Assert.False(s.FocusClickedWidgetOnRaise);
        Assert.Empty(s.DeletedWidgetIds);
        Assert.True(s.WeatherAutoLocation);
        Assert.Equal(string.Empty, s.WeatherCityName);
        Assert.Equal(0d, s.WeatherLatitude);
        Assert.Equal(0d, s.WeatherLongitude);
        Assert.Equal("Celsius", s.WeatherTemperatureUnit);
        Assert.Equal("kmh", s.WeatherWindSpeedUnit);
        Assert.Equal("MSN", s.WeatherDataSource);
        Assert.Equal("Today", s.WeatherDefaultView);
        Assert.Equal("Standard", s.WeatherSkin);
        Assert.True(s.WeatherShowForecast);
        Assert.True(s.WeatherShowSunrise);
        Assert.True(s.WeatherShowUvIndex);
        Assert.True(s.WeatherShowPrecipitation);
        Assert.True(s.WeatherShowHumidity);
        Assert.True(s.WeatherShowWind);
        Assert.False(s.WeatherShowPressure);
        Assert.Equal(60, s.WeatherRefreshIntervalMinutes);
        Assert.False(s.SearchHotkeyEnabled);
        Assert.Equal((int)HotkeyModifierKeys.Alt, s.SearchHotkeyModifiers);
        Assert.Equal(0x44, s.SearchHotkeyKey);
        Assert.Equal("Spotlight", s.SearchDisplayMode);
        Assert.True(s.SearchIncludeDeskBoxContent);
        Assert.False(s.SearchEverythingEnabled);
        Assert.Equal(string.Empty, s.SearchEverythingExecutablePath);
        Assert.False(s.SearchEverythingAdvancedSyntaxEnabled);
        Assert.True(s.SearchShowRecommendations);
        Assert.True(s.SearchSaveHistory);
        Assert.Equal(100, s.SearchMaxResults);
        Assert.Equal("all", s.SearchDefaultTab);
        Assert.Equal(0, s.SearchAppIconAnimation);
        Assert.Null(s.SearchPopupCustomX);
        Assert.Null(s.SearchPopupCustomY);
        Assert.Null(s.SearchPopupCustomWidth);
        Assert.Null(s.SearchPopupCustomHeight);
        Assert.Equal("none", s.CloudBackupProvider);
        Assert.Equal("", s.CloudBackupServerUrl);
        Assert.Equal("DeskBox/backups", s.CloudBackupRemotePath);
        Assert.Equal("", s.CloudBackupUsername);
        Assert.False(s.CloudBackupTodoDataEnabled);
        Assert.False(s.CloudBackupQuickCaptureDataEnabled);
        Assert.False(s.CloudBackupWidgetStyleEnabled);
        Assert.Equal(5, s.CloudBackupRetentionCount);
        Assert.Equal(24 * 60, s.CloudBackupIntervalMinutes);
        Assert.Equal(0L, s.CloudBackupLastSuccessUtcTicks);
        Assert.Equal(0L, s.CloudBackupLastFailureUtcTicks);
    }

    [Fact]
    public void SerializedMemberOrder_MatchesPreSliceDeclarationOrder()
    {
        // Legacy prop set so the WhenWritingNull member is emitted too.
        var s = new AppSettings { LegacyWidgetCapsuleModeEnabled = true };
        using var doc = System.Text.Json.JsonDocument.Parse(
            System.Text.Json.JsonSerializer.Serialize(
                s, DeskBox.Services.SettingsJsonContext.Default.AppSettings));
        string[] actual = doc.RootElement.EnumerateObject()
            .Select(p => p.Name).ToArray();
        Assert.Equal(ExpectedMemberOrder, actual);
    }

    private static readonly string[] ExpectedMemberOrder =
    [
        "schemaVersion",
        "theme",
        "trayIconStyle",
        "language",
        "accentColorMode",
        "customAccentColor",
        "autoStart",
        "autoStartDefaultApplied",
        "autoStartMode",
        "performanceMode",
        "hiddenCacheCleanupDelaySeconds",
        "hiddenCacheCleanupScope",
        "visibleIdleCacheCleanupDelaySeconds",
        "idleWorkingSetTrimEnabled",
        "immediateHiddenWorkingSetTrimEnabled",
        "quiescenceWorkingSetTrimEnabled",
        "transientWindowReleaseDelaySeconds",
        "performanceCacheBudget",
        "enableContinuousDecorativeAnimations",
        "enableTextMarqueeAnimations",
        "enableVinylRotationAnimations",
        "enableGlanceImageAutoRotation",
        "enableCompactAmbientAnimations",
        "autoCheckForUpdates",
        "lastUpdateCheckAt",
        "quickCaptureEnabled",
        "todoEnabled",
        "featureWidgetEnabledStates",
        "quickCaptureClipboardEnabled",
        "quickCaptureImageClipboardEnabled",
        "quickCaptureRecentLimit",
        "quickCaptureShowCreatedTime",
        "quickCaptureItemPreviewLineCount",
        "quickCaptureListTextSize",
        "quickCaptureContentTextSize",
        "quickCaptureEditorEnterBehavior",
        "quickCaptureDefaultFormat",
        "quickCaptureWideLayout",
        "quickCaptureWideOpenMode",
        "quickCaptureAllowRemoteImages",
        "attachmentStorageMode",
        "quickCaptureDefaultView",
        "quickCaptureTabStyle",
        "quickCaptureShowTabBar",
        "quickCaptureShowRecordsTab",
        "quickCaptureShowPinnedTab",
        "quickCaptureShowRecentTab",
        "todoNewTaskPosition",
        "todoTabStyle",
        "todoShowTabBar",
        "todoShowAllTab",
        "todoShowActiveTab",
        "todoShowTodayTab",
        "todoShowThisWeekTab",
        "todoShowThisMonthTab",
        "todoShowImportantTab",
        "todoShowCompletedTab",
        "todoDefaultFilter",
        "todoShowCompletedTasks",
        "todoItemPreviewLineCount",
        "todoListTextSize",
        "todoContentTextSize",
        "todoEditorEnterBehavior",
        "todoShowFooterStats",
        "todoShowClearCompletedButton",
        "todoReminderEnabled",
        "todoDefaultReminderOffsetMinutes",
        "todoUseWideDetailPane",
        "todoLayoutMode",
        "todoAutoSelectFirstInWideLayout",
        "musicUseArtworkBackdrop",
        "musicEnableCoverHoverMotion",
        "musicDisplayMode",
        "lastQuickCaptureFileWidgetId",
        "globalHotkeyEnabled",
        "globalHotkeyActivationKind",
        "globalHotkeyModifiers",
        "globalHotkeyKey",
        "desktopDoubleClickEnabled",
        "hasCompletedOnboarding",
        "onboardingStepIndex",
        "completedOnboardingVersion",
        "hasResolvedInitialFileWidgetSetup",
        "defaultWidgetWidth",
        "defaultWidgetHeight",
        "widgetOpacity",
        "widgetMaterialType",
        "widgetMaterialIntensity",
        "widgetForegroundMode",
        "widgetForegroundColor",
        "widgetBorderColorMode",
        "widgetBorderStyle",
        "widgetCornerPreference",
        "widgetAnimationEffect",
        "widgetAnimationSpeed",
        "widgetAnimationSlideDirection",
        "widgetAnimationEasingIntensity",
        "widgetLayerMode",
        "keepWidgetsVisibleOnShowDesktop",
        "displayWidgetChromeMode",
        "interactiveWidgetChromeMode",
        "widgetCollapseBehavior",
        "widgetCapsuleModeEnabled",
        "widgetCompactWidthMode",
        "widgetCompactExpansionDirection",
        "widgetCapsuleArrangementMode",
        "widgetCapsuleBarSpacing",
        "widgetCapsuleBarPlacement",
        "widgetCapsuleBarDirection",
        "widgetCapsuleBarOrder",
        "widgetCapsuleFreePlacements",
        "widgetCollapsedStyle",
        "widgetCompactContentMode",
        "widgetCompactHideSensitiveContent",
        "widgetCompactSettingsVersion",
        "widgetCompactAnimationEffect",
        "widgetCompactAnimationDurationMs",
        "widgetCompactExpandDelayMs",
        "widgetCompactCollapseDelayMs",
        "widgetCompactMediaCornerMode",
        "widgetTitleIconMode",
        "doubleClickToOpen",
        "fileWidgetFolderOpenBehavior",
        "fileItemSystemContextMenuEnabled",
        "hideShortcutArrowOverlay",
        "showImageFilesAsIcons",
        "showHoverButtons",
        "widgetHoverButtonActions",
        "resizeSnapEnabled",
        "widgetSnapSpacing",
        "showListItemDetails",
        "showFileItemPathTooltips",
        "fileStacksEnabled",
        "fileStackAutoStacking",
        "fileStackGroupBy",
        "fileStackThreshold",
        "fileStackOrderBy",
        "fileStackOpenMode",
        "fileStackPopoverLayout",
        "fileStackPopoverStyle",
        "fileStackCustomRules",
        "fileStackUnmatchedBehavior",
        "managedDropAction",
        "defaultManagedStorageRootPath",
        "managedStorageDesktopShortcutEnabled",
        "managedStorageDesktopShortcutPath",
        "automaticBackupEnabled",
        "automaticBackupIntervalMinutes",
        "automaticBackupRetentionCount",
        "automaticBackupDirectory",
        "recentOrganizationHistory",
        "desktopOrganizationRules",
        "desktopAutoOrganizationEnabled",
        "desktopAutoOrganizationBaselineUtc",
        "iconSize",
        "textSize",
        "layoutDensity",
        "layoutDensityScale",
        "horizontalSpacingScale",
        "verticalSpacingScale",
        "fileNameWidthScale",
        "fileNameLineCount",
        "showFileExtensions",
        "hideShortcutExtensionWhenShowingFileExtensions",
        "widgets",
        "widgetGroups",
        "widgetTopologyLayouts",
        "activeWidgetTopologyKey",
        "widgetGroupsEnabled",
        "widgetGroupDefaultNavigationStyle",
        "widgetGroupDefaultTitleDisplayMode",
        "widgetGroupWheelSwitchEnabled",
        "widgetGroupHoverSwitchEnabled",
        "focusClickedWidgetOnRaise",
        "deletedWidgetIds",
        "weatherAutoLocation",
        "weatherCityName",
        "weatherLatitude",
        "weatherLongitude",
        "weatherTemperatureUnit",
        "weatherWindSpeedUnit",
        "weatherDataSource",
        "weatherDefaultView",
        "weatherSkin",
        "weatherShowForecast",
        "weatherShowSunrise",
        "weatherShowUvIndex",
        "weatherShowPrecipitation",
        "weatherShowHumidity",
        "weatherShowWind",
        "weatherShowPressure",
        "weatherRefreshIntervalMinutes",
        "searchHotkeyEnabled",
        "searchHotkeyModifiers",
        "searchHotkeyKey",
        "searchDisplayMode",
        "searchIncludeDeskBoxContent",
        "searchEverythingEnabled",
        "searchEverythingExecutablePath",
        "searchEverythingAdvancedSyntaxEnabled",
        "searchShowRecommendations",
        "searchSaveHistory",
        "searchMaxResults",
        "searchDefaultTab",
        "searchAppIconAnimation",
        "searchPopupCustomX",
        "searchPopupCustomY",
        "searchPopupCustomWidth",
        "searchPopupCustomHeight",
        "cloudBackupProvider",
        "cloudBackupServerUrl",
        "cloudBackupRemotePath",
        "cloudBackupUsername",
        "cloudBackupTodoDataEnabled",
        "cloudBackupQuickCaptureDataEnabled",
        "cloudBackupWidgetStyleEnabled",
        "cloudBackupRetentionCount",
        "cloudBackupIntervalMinutes",
        "cloudBackupLastSuccessUtcTicks",
        "cloudBackupLastFailureUtcTicks",
        "cloudBackupLastUnverifiedUtcTicks",
    ];
}
